### PR TITLE
JOSS paper writeup

### PR DESCRIPTION
**Pull request by zhengp0**
Overwrite #22

### CODE REVIEW

**Comment by zhengp0** [comment]
Hey @saravkin! I added the paragraph in the "core idea" section, please let me know what you think. And please let me know if we need a figure there somehow to show case, in case the example I provided in the documentation isn't enough.

**Comment by saravkin** [comment]
Hi @zhengp0 ! I made minor edits to the 'core idea' paragraph. I love the usage page link, and the documentation looks great, I think you can go ahead and submit to JOSS. :)

**Review by saravkin — APPROVED** [review]
Looks good! Sorry I did this out of order, I made a commit to the readme and then I realized I could review the request. 

Not trying to add chaos here, just being myself. :)

**Comment by zhengp0** [comment]
Thanks @saravkin! Will merge the branch now.

**Pull request merged**
